# Generated by Django 3.2.8 on 2023-01-15 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20230115_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_Admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='last_login_time',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='register_time',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
