# Generated by Django 3.2.8 on 2023-01-15 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20230115_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='last_login_time',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='register_time',
            field=models.DateField(),
        ),
    ]
