# Generated by Django 3.2.16 on 2023-02-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_userinfo2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo2',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
